### ISSUE TITLE
ValueError: expected 5D input (got 4D input)

### ISSUE THREAD

**Issue by usingcsharp** [GordonRen/edge2view#1]
Hello,I find you question in 'Torch2CoreML' project, 
def _check_input_dim(self, input):
    reshape (N,C,H,W) to (N,C,1,H,W) 
         if input.dim() != 5:
            raise ValueError('expected 5D input (got {}D input)'
                             .format(input.dim()))
But I can't work well, can you help me? Thank you very much!

**Comment by GordonRen** [comment]
https://github.com/prisma-ai/torch2coreml/issues/27
